import {Selector } from 'testcafe';

const eaCheckoutDetailsPage={
  elements: {
    myDetailsHeaderText:Selector('#myDetailsTitle'),
    titleDropdown:Selector('#title-active-option'),
    titleTag:Selector("[name='title'] .ea-dropdown__options li"),
    firstName:Selector('#firstname'),
    lastName:Selector('#lastname'),
    dob:Selector('#dob'),
    dobDay:Selector('#dob-day'),
    dobMonth:Selector('#dob-month'),
    dobYear:Selector('#dob-year'),
    email:Selector('#email'),
    phone:Selector('#phone'),
    idDrop:Selector('#id-type-active-option'),
    idValueDriverLicense:Selector('#edit-id-type-dl'),
    idValuePassport:Selector('#edit-id-type-passport'),
    idValueMedicare:Selector('#edit-id-type-medicare'),
    idNumber:Selector('#identification-value'),
    idLicenseNumber:Selector('#drivers-licence-number'),
    stateOfIssue:Selector('#drivers-licence-state-active-option'),
    stateOfIssueDropdown:Selector('#drivers-licence-state-active-option').parent().sibling().find('li'),
    idPassportNumber:Selector('#passport-number'),
    idCountry:Selector('#country-of-issue'),
    medicareColorGreen:Selector('#edit-medicare-cards-green__label'),
    medicareColorBlue:Selector('#edit-medicare-cards-blue__label'),
    medicareColorYellow:Selector('#edit-medicare-cards-yellow__label'),
    idMedicareNumber:Selector('#medicare-card-number'),
    idMedicareRef:Selector('#medicare-reference-number'),
    idMedicareValid:Selector('#medicare-expiry'),
    idMedicareValidDD:Selector('#id_validTo-day'),
    idMedicareValidMM:Selector('#id_validTo-month'),
    idMedicareValidYYYY:Selector('#id_validTo-year'),
    idMedicareValidYY:Selector('#id_validTo-year+input'),
    electricityAccessNo:Selector('#option-accessissuesele-false'),
    gasAccessNo: Selector('#option-accessissuesgas-false'),
    reviewYourOrderBtn:Selector('#reviewAgreeConfirmButton'),
    ABN:Selector('#edit-business-identifier-type-abn__label'),
    ACN:Selector('#edit-business-identifier-type-acn__label'),
    inputABNNumber:Selector('#abn-number'),
    inputACNNumber:Selector('#acn-number'),
    company:Selector('#business-name'),
    businessType:Selector('#business-type-active-option'),
    businessTypeOption:Selector('#business-type-active-option').parent().sibling().find('li'),
    anzsicCode:Selector('#anzsic-code-active-option'),
    anzsicCodeOption:Selector('#anzsic-code-active-option').parent().sibling().find('li'),
    prevHomeImproveNo:Selector('#edit-previous-home-renovations-no__label'),
    planHomeImproveNo:Selector('#edit-planned-home-renovations-no__label'),
    renovationNo:Selector('#edit-planned-renovations-no__label'),
    addAAH: Selector("#aah__add"),
    aahFirstName: Selector("#aah-first-name"),
    aahLastName: Selector("#aah-last-name"),
    aahEmail: Selector("#aah-email"),
    aahPermissionLvl1: Selector("#edit-aah-access-type-read__label"),
    aahPermissionLvl2: Selector("#edit-aah-access-type-read-write__label"),
    aahPermissionLvl3: Selector("#edit-aah-access-type-full__label"),
    slickDotsAAH:Selector("#additional-account-holder ul.slick-dots>li"),
    slickDotsDD:Selector("#direct-debit ul.slick-dots>li"),
    addDirectDebit: Selector("#direct-debit__add"),
    tfBankAccountName: Selector("#bankAccountName"),
    tfBsb: Selector("#bsb"),
    tfBankAccountNumber: Selector("#bankAccountNumber"),
    cbBankAccountAgreeTermsAndCond: Selector("#baAgree"),
    useCC: Selector("#edit-direct-debit-cc__label"),
    tfCCName: Selector("#creditCardName"),
    tfCCNumber: Selector("#creditCardNumber"),
    tfCCExpiry: Selector("#creditCardExpiry"),
    cbCCAgreeTermsAndCond: Selector("#ccAgree"),
    rbDisconnectionYes:Selector("#edit-disconnecting-yes__label"),
    rbDisconnectionNo:Selector("#edit-disconnecting-no__label"),
    rdbEleAccessRestrictionNo:Selector("#edit-ele-access-restrictions-no__label"),
    rdbGasAccessRestrictionNo:Selector("#edit-gas-access-restrictions-no__label"),
    eleDisconnectionError:Selector("#electricity-disconnection-calendar-error"),
    gasDisconnectionError:Selector("#gas-disconnection-calendar-error"),
    eleDisconnectionCalendar: Selector("#electricity-calendar table"),
    gasDisconnectionCalendar: Selector("#gas-calendar table"),
    basicElePlan:Selector("[id*='plan-select-button-RSOT-E']"),
    basicQLDElePlan:Selector("[id*='plan-select-button-GRT-E']"),
    noFrillsElePlan:Selector("[id*='plan-select-button-RCPP-E']"),
    totalElePlan: Selector("[id*='plan-select-button-TOPH-E']"),
    totalPlanPlusEle:Selector("[id*='plan-select-button-SWSR1-E']"),
    basicEleBusiness:Selector("[id*='plan-select-button-BSOT-E']"),
    basicQLDEleBusiness:Selector("[id*='plan-select-button-BGRT-E']"),
    noFrillEleBusiness:Selector("[id*='plan-select-button-BCPP-E']"),
    totalElePlanBusiness:Selector("[id*='plan-select-button-TOPB-E']"),
    totalPlanPlusEleBusiness:Selector("[id*='plan-select-button-SWSRB-E']"),
    basicGasPlan:Selector("[id*='plan-select-button-RSOT-G']"),
    noFrillsGasPlan:Selector("[id*='plan-select-button-RCPP-G']"),
    totalGasPlan: Selector("[id*='plan-select-button-TOPH-G']"),
    totalPlanPlusGas:Selector("[id*='plan-select-button-SWSR1-G']"),
    basicGasBusiness:Selector("[id*='plan-select-button-BSOT-G']"),
    noFrillGasBusiness:Selector("[id*='plan-select-button-BCPP-G']"),
    totalGasPlanBusiness:Selector("[id*='plan-select-button-TOPB-G']"),
    totalPlanPlusGasBusiness:Selector("[id*='plan-select-button-SWSRB-G']"),
    txtMySelection:Selector("#connDetailsTitle"),
    elePlansExpand:Selector("#select-plan-ELE .select-plan-expanded"),
    gasPlansExpand:Selector("#select-plan-GAS .select-plan-expanded"),
    chkboxCarbonNeutral:Selector("[name='carbonNeutralOptIn'] label"),
    rbBillPrefEmail: Selector("#edit-bill-delivery-email__label"),
    rbBillPrefPost: Selector("#edit-bill-delivery-post__label"),
    rbBillPrefOtherAddress: Selector("#bill-delivery-method__other-address-option div"),
    tfBillPrefOtherAddress: Selector("#bill-delivery-other-address-auto-input"),
    serviceAddressList: Selector("#mailingAddress-auto-autocomplete li"),
    rbFinalBillPrefEmail: Selector("#edit-final-bill-email__label"),
    rbFinalBillPrefConnectionAddress: Selector("#edit-final-bill-connection-address__label"),
    rbFinalBillPrefOtherAddress: Selector("#edit-final-bill-other-address__label"),
    tfFinalBillPrefOtherAddress: Selector("#address-auto-input"),
    finalBillServiceAddressList: Selector("#address-auto-autocomplete li"),
    addConcession: Selector("#concession__add"),
    concessionCardTypeDropDown: Selector("#concession-cardtype-active-option"),
    concessionCardTypeOption: Selector("#concession-cardtype-active-option").parent().sibling().find("li"),
    tfConcessionCardNumber: Selector("#concession_cardnumber"),
    cbConcessionAgreeTerms: Selector("[name='concession_agreeTerms'] label"),
    cbOptInCarbonNeutral: Selector("#carbonNeutralOptIn"),
    eaSpinner:Selector(".ea-spinner.ng-star-inserted"),
    linkNeedHelp:Selector("#ea-fab-toggle-button"),
    pageTitleBlock: Selector("[data-block-plugin-id*='page_title_block']"),
    txtPageTitle: Selector("[data-block-plugin-id*='page_title_block'] .page-title"),
    btnCloseText: Selector("[data-block-plugin-id*='page_title_block'] .page-header__link-text"),
    linkClose: Selector("[data-block-plugin-id*='page_title_block'] a"),
    progressBar: Selector("div[role*='main'] .checkout-progress-bar"),
    progressBarProgressIndicatorCompleted: Selector("div[role*='main'] .checkout-progress-bar span[class='completed']"),
    txtSubheading: Selector("#checkout-progress-bar-subheading"),
    basicResiElePlanRateSummary:Selector("[id*='plan-rate-summary-title-RSOT-E']"),
    basicResiElePlanFeatureTitle:Selector("[id*='plan-feature-title-RSOT-E']"),
    basicResiElePlanRatesTitle:Selector("[id*='plan-rates-title-RSOT-E']"),
    basicResiGasPlanFeatureTitle:Selector("[id*='plan-feature-title-RSOT-G']"),
    basicResiGasPlanRatesTitle:Selector("[id*='plan-rates-title-RSOT-G']"),
    basicBsmeElePlanFeatureTitle:Selector("[id*='plan-feature-title-BSOT-E']"),
    basicBsmeElePlanRatesTitle:Selector("[id*='plan-rates-title-BSOT-E']"),
    basicBsmeGasPlanFeatureTitle:Selector("[id*='plan-feature-title-BSOT-G']"),
    basicBsmeGasPlanRatesTitle:Selector("[id*='plan-rates-title-BSOT-G']"),
    sliderRight:Selector("div.hs-plan-slider__button__bg-right"),
    connectionAddress:Selector("#connAddrTitle"),
    chkboxSpecialOffer:Selector("#special-offers label"),
    preferredCommEmail:Selector("#edit-preferred-communication-method-email__label"),
    preferredCommPost:Selector("#edit-preferred-communication-method-post__label"),
    mailingAddrAsConnAddr:Selector("#edit-mailingmethod-connection-address__label"),
    mailingAddrAsOtherAddr:Selector("#edit-mailingmethod-alternative-address__label"),
    inputMailingAddrAsOtherAddr:Selector("#mailingAddress-auto-input"),
    contactPreference: {
      disclaimer: Selector(".hs-contact-preference__text"),
      linkClickHere: Selector("#contact-opt-out-modal"),
      modalHeading: Selector("[id*='ContactPreferenceModalId'].ea-modal__heading"),
      lblModalText: Selector("[for*='contactPreferenceOptIn']"),
      btnSubmit: Selector("[modaltitle*='Contact preference'] button[class*='primary']"),
      btnClose: Selector("[modaltitle*='Contact preference'] button[class*='white']")
    },
    refineBar: {
      main: Selector(".checkout__container .refine-toggle-bar"),
      refinePeriod: Selector("#refine-period"),
      gasUsage: Selector("#refine-gas-usage"),
      eleUsage: Selector("#refine-ele-usage"),
      greenEnergy: Selector("#refine-green")
    },
    currentPlan:{
      planTable:Selector("[id*='plan-table-current-plan-']"),
      planDetailsSection:Selector("[id*='plan-table-current-plan-'] [id*='plan-details-']"),
      planDetailsTitle:Selector("[id*='plan-table-current-plan']>div[id*='plan-details-title']"),
      planHeadingTitle:Selector("[id*='plan-table-current-plan']>div[id*='plan-heading'] #plan-heading-title-CURRENT_ELE"),
      planHeadingFuel:Selector("[id*='plan-table-current-plan']>div[id*='plan-heading'] #plan-heading-fuel-CURRENT_ELE"),
      planEstimate:Selector("[id*='plan-table-current-plan']>div[id*='plan-estimate']"),
      planGSTDisclaimer:Selector("[id*='plan-table-current-plan']>div[id*='plan-gst-disclaimer']"),
      discounts:Selector("[id*='plan-table-current-plan']>div[id*='plan-details-discounts']"),
      //benefitPeriod:Selector("[id*='plan-table-current-plan']>div[id*='plan-details-benefit-period']"),
      exitFees:Selector("[id*='plan-table-current-plan']>div[id*='plan-details-exit-fees']"),
      customerType:Selector("[id*='plan-table-current-plan']>div[id*='plan-details-customer-tariff-type']"),
      planEleRateAccordion:Selector("[id*='plan-table-current-plan']>div[id*='plan-ELE-rate-accordion-heading']"),
      disclaimer:Selector("[id*='plan-table-current-plan']>div[id*='current-plan-disclaimer']"),
      sliderRight:Selector("div.hs-plan-slider__button__bg-right"),
      sliderLeft:Selector("div.hs-plan-slider__button__bg-left"),
    },

    btnSelectPlan: Selector("[id*='plan-select-button'] .hs-plan-table__plan-button-text-desktop"),
    txtFeesDisclaimer: Selector(".hs-plan-fees__card"),
    txtPaperBillFeeDisclaimer: Selector("#hs-plan-fees-paper-bill"),
    btnNext:Selector("#select-plans-next"),
    btnBack:Selector("#select-plans-back"),
    removeAAH: Selector("#additional-account-holder__remove"),
    removeDirectDebit: Selector("#direct-debit__remove"),
    removeConcession: Selector("#concession-card__remove")
  },
};

module.exports=eaCheckoutDetailsPage;
