import {Selector } from 'testcafe';

const eaNewConnectionPage={
  elements: {
      txtConnectionDetails:Selector(".section>div>h2"),
      btnSelectEle:Selector("#option-fuel-type-electricity+label"),
      btnSelectGas:Selector("#option-fuel-type-gas+label"),
      btnSelectCommercial:Selector("#option-property-type-commercial+label"),
      btnSelectResidential:Selector("#option-property-type-residential+label"),
      btnSelectSinglePremise:Selector("#option-premise-types-single+label"),
      btnSelectUnitDevpremise:Selector("#option-premise-types-unit-development+label"),
      txtLotNo:Selector("input[name='lotNo_input']"),
      txtStreetNo:Selector("input[name='streetNo_input']"),
      txtStreetName:Selector("input[name='streetName_input']"),
      txtSuburb:Selector("input[name='suburb_input']"),
      listActiveState   :Selector("div[title='Please select']>div>sui-select[class*='sui-select-wrap']"),
      selectStateFromDropdown:Selector("div[title='Please select']>div>sui-select[class*='sui-select-wrap'] div.sui-dropdown>sui-option"),
      txtPostcode:Selector("input[name='postcode_input']"),
      btnProceedToStep2:Selector("#next-step-1"),
      inputInstallingPoleNo:Selector("#option-installing-builders-pole-on-site-no+label"),
      inputInstallingPoleYes:Selector("#option-installing-builders-pole-on-site-yes+label"),
      inputPeakLoadNo:Selector("#option-network-tariff-has-off-peak-loads-no+label"),
      inputPeakLoadYes:Selector("option-network-tariff-has-off-peak-loads-yes+label"),
      btnProceedToStep3:Selector("#next-step-2"),
      txtFirstname:Selector("input[name='applicantFirstName_input']"),
      txtLastname:Selector("input[name='applicantLastName_input']"),
      txtMobileNo:Selector("input[name='applicantMobile_input']"),
      txtEmail:Selector("input[name='applicantEmail_input']"),
      txtPlumberFirstname:Selector("input[name='plumberFirstName_input']"),
      txtPlumberLastname:Selector("input[name='plumberLastName_input']"),
      txtPlumberMobileNo:Selector("input[name='plumberMobile_input']"),
      txtPlumberLandline:Selector("input[name='plumberLandline_input']"),
      txtPlumberEmail:Selector("input[name='plumberEmail_input']"),
      txtPlumberLicenseNumber:Selector("input[name='licenceNumber_input']"),
      txtPlumberComplianceNumber:Selector("input[name='complianceNumber_input']"),
      txtPlumberESVNo:Selector("input[name='esvNo_input']"),
      inputSameAsApplicant:Selector("#option-account-holder-type-same-as-applicant-s-details+label"),
      txtDOB_dd:Selector("input[name='dateOfBirth_dd']"),
      txtDOB_mm:Selector("input[name='dateOfBirth_mm']"),
      txtDOB_yyyy:Selector("input[name='dateOfBirth_yyyy']"),
      applicantIdTypeActive: Selector("#idType sui-select"),
      idType:Selector("#idType sui-select div.sui-dropdown>sui-option"),
      txtIdNo:Selector("input[name='idNumber_input']"),
      applicantIdStateActive:Selector("#idState sui-select"),
      idState:Selector("#idState sui-select div.sui-dropdown>sui-option"),
      inputSameasSiteAddress:Selector("#option-mailing-address-source-same-as-site-address+label"),
      acceptTermsAndConds:Selector("#option-tc-selected+label"),
      submitForm:Selector("#submit-request"),
      btnProceedToQuote:Selector("button[ng-click*='proceedToCompleteYourQuote']"),
      connectionType_MeterInstall:Selector("#option-connection-type-meter-installation+label"),
      connectionType_ServiceLineInstall:Selector("#option-connection-type-meter-installation+label"),
      inputServicelineInstallYes:Selector("#option-service-line-installed-yes+label"),
      inputServicelineInstallNo:Selector("#option-service-line-installed-no+label"),
      inputSiteClearYes:Selector("#option-site-clear-yes+label"),
      inputSiteClearNo:Selector("#option-site-clear-no+label"),
      inputSiteMarkedYes:Selector("#option-site-marked-yes+label"),
      inputSiteMarkedNo:Selector("#option-site-marked-no+label"),
      btnProceedToStep4:Selector("#next-step-3"),
      inputBelowAMPS:Selector("#option-amps-below-140-amps+label"),
      inputAboveAMPS:Selector("#option-amps-over-140-amps+label"),
      plumberTitleActive:Selector("#plumberTitle sui-select"),
      plumberTitle:Selector("#plumberTitle sui-select>div.sui-dropdown>sui-option[value='Mr']"),
      applicantTitleActive:Selector("#applicantTitle sui-select"),
      applicantTitle:Selector("#applicantTitle sui-select>div.sui-dropdown>sui-option[value='Mr']"),
      connectionDetailSection:Selector("#connectionDetails"),
      hotWaterField:Selector("table.appliances-type-table>tbody>tr:nth-of-type(2) td>input"),
  },
};

module.exports=eaNewConnectionPage;
