import {Selector } from 'testcafe';

const eaNewConnectionPage={
  elements: {
    txtConnectionDetails:Selector(".section>div>h2"),
    btnSelectEle:Selector("[for=edit-fuel-type-ele]"),
    btnSelectGas:Selector("[for=edit-fuel-type-gas]"),
    btnSelectCommercial:Selector("[for=edit-property-type-commercial]"),
    btnSelectResidential:Selector("[for=edit-property-type-residential]"),
    btnSelectSinglePremise:Selector("[for=edit-premise-type-single]"),
    btnSelectUnitDevpremise:Selector("[for=edit-premise-type-unit-development]"),
    txtUnitNo:Selector("#pa-unit-number"),
    txtLotNo:Selector("#pa-lot-number"),
    txtStreetNo:Selector("#pa-street-number"),
    txtStreetName:Selector("#pa-street-name"),
    textStreetSuffix:Selector("#pa-street-suffix"),
    txtSuburb:Selector("#pa-suburb"),
    listActiveState   :Selector("#pa-state-active-option"),
    selectStateFromDropdown:Selector("div.ea-dropdown__wrapper+ul>li"),
    txtPostcode:Selector("#pa-postcode"),
    txtSubDivisionNo:Selector("#pa-sub-division-number"),
    btnNext:Selector("#next"),
    inputInstallingPoleNo:Selector("[for=edit-temporary-builders-pole-option-no]"),
    inputInstallingPoleYes:Selector("[for=edit-temporary-builders-pole-option-yes]"),
    inputInstallingPoleUnknown:Selector("[for=edit-temporary-builders-pole-option-unknown]"),
    inputPeakLoadNo:Selector("[for=edit-off-peak-loads-option-no]"),
    inputPeakLoadYes:Selector("[for=edit-off-peak-loads-option-yes]"),
    inputPeakLoadUnknown:Selector("[for=edit-off-peak-loads-option-unknown]"),
    txtFirstname:Selector("#applicant-details-first-name"),
    txtLastname:Selector("#applicant-details-last-name"),
    txtMobileNo:Selector("#applicant-details-mobile-number"),
    txtEmail:Selector("#applicant-details-email"),
    txtPlumberFirstname:Selector("input[name='plumberFirstName_input']"),
    txtPlumberLastname:Selector("input[name='plumberLastName_input']"),
    txtPlumberMobileNo:Selector("input[name='plumberMobile_input']"),
    txtPlumberLandline:Selector("input[name='plumberLandline_input']"),
    txtPlumberEmail:Selector("input[name='plumberEmail_input']"),
    txtPlumberLicenseNumber:Selector("input[name='licenceNumber_input']"),
    txtPlumberComplianceNumber:Selector("input[name='complianceNumber_input']"),
    txtPlumberESVNo:Selector("input[name='esvNo_input']"),
    inputSameAsApplicant:Selector("[for=edit-account-holder-type-same-as-applicants-details]"),
    txtDOB:Selector("#account-holder-dob"),
    applicantIdTypeActive: Selector("#identification-option-active-option"),
    idTypeDl:Selector("#edit-identification-option-drivers-licence"),
    idTypeMedicare:Selector("#edit-identification-option-medicare"),
    idTypePassport:Selector("#edit-identification-option-passport"),
    idType:Selector("#idType sui-select div.sui-dropdown>sui-option"),
    txtIdNo:Selector("#identification-number"),
    applicantIdStateActive:Selector("#identification-state-option-active-option"),
    idStateVIC:Selector("#edit-identification-state-option-vic"),
    idStateACT:Selector("#edit-identification-state-option-act"),
    idStateNSW:Selector("#edit-identification-state-option-nsw"),
    idStateSA:Selector("#edit-identification-state-option-sa"),
    idStateTAS:Selector("#edit-identification-state-option-tas"),
    idStateNT:Selector("#edit-identification-state-option-nt"),
    idStateQLD:Selector("#edit-identification-state-option-qld"),
    idStateWA:Selector("#edit-identification-state-option-wa"),
    idStateInternational:Selector("edit-identification-state-option-international"),
    inputSameAsSiteAddress:Selector("[for=edit-mailing-address-question-same-as-site-address]"),
    acceptTermsAndConds:Selector("[for=terms-and-conditions-field]"),
    submitForm:Selector("#next"),
    btnProceedToQuote:Selector("button[ng-click*='proceedToCompleteYourQuote']"),
    connectionType_MeterInstall:Selector("#option-connection-type-meter-installation+label"),
    connectionType_ServiceLineInstall:Selector("#option-connection-type-meter-installation+label"),
    inputServicelineInstallYes:Selector("#option-service-line-installed-yes+label"),
    inputServicelineInstallNo:Selector("#option-service-line-installed-no+label"),
    inputSiteClearYes:Selector("#option-site-clear-yes+label"),
    inputSiteClearNo:Selector("#option-site-clear-no+label"),
    inputSiteMarkedYes:Selector("#option-site-marked-yes+label"),
    inputSiteMarkedNo:Selector("#option-site-marked-no+label"),
    btnProceedToStep4:Selector("#next-step-3"),
    inputBelowAMPS:Selector("#option-amps-below-140-amps+label"),
    inputAboveAMPS:Selector("#option-amps-over-140-amps+label"),
    plumberTitleActive:Selector("#plumberTitle sui-select"),
    plumberTitle:Selector("#plumberTitle sui-select>div.sui-dropdown>sui-option[value='Mr']"),
    applicantTitleActive:Selector("#applicant-details-title-active-option"),
    applicantTitle:Selector("#edit-applicant-details-title-mr"),
    connectionDetailSection:Selector("#connectionDetails"),
    hotWaterField:Selector("table.appliances-type-table>tbody>tr:nth-of-type(2) td>input"),
  },
};

module.exports=eaNewConnectionPage;
